#!/usr/bin/python
import csv
import pandas as pd
import numpy as np
import time
import sys
import random
import scpclient
import md5
import subprocess
import os
import socket
import smtplib
from pandas import DataFrame
from sqlalchemy import create_engine
import massedit


# Golbal Variable
datenow=(time.strftime("%Y-%m-%d:%T"))
COS_LIST='/opt/ams_smart/var/cos_list.csv'
CATALOG='/opt/ams_smart/var/catalog.csv'
filename=sys.argv[1]
ADEX_FILE='/SMART/OUT/AD_STG/adexchange-'+datenow+'.csv'
ZM_FILE='/SMART/OUT/ZM_STG/adzimbra-'+datenow+'.csv'
IMPORT_DB='/SMART/OUT/DB_IMPORT/importdb-'+datenow+'.csv'
ACCOUNT_EXIST='/SMART/OUT/VALIDATION/account_exist-'+datenow+'.csv'
ZM_SVR="10.58.122.209"

# convert delimiter 
massedit.edit_files(filename, ["re.sub(r',', ';', line)"], dry_run=True)
print (massedit)

#-- DB Engine
engine = create_engine("mysql://root:paganini@localhost/homecredit")


#dataframe database_check
query_check = "select nik,email from tbl_users"
source_db = pd.read_sql(query_check, engine)
source_db.columns=['EMP_NO','EMAIL']
print (source_db)

#Global Column MANDATORY
#df = pd.read_csv(filename, usecols=['EMP_NO','USERNAME','FIRST_NAME','LAST_NAME','EMAIL','AD','EXCHANGE','POSITION','CITY','SUPERVISOR','PASSWORD','WORK_LOCATION','COST_CENTER','MOBILE_PHONE','TICKET','POS_ID','EMPLOYEE_NAME'], delimiter=',')
#df = pd.read_csv(filename, delimiter=',')
df = pd.read_csv(filename, usecols=['EMP_NO','USERNAME','FIRST_NAME','LAST_NAME','EMAIL','AD','EXCHANGE','POSITION','CITY','SUPERVISOR','PASSWORD','WORK_LOCATION','COST_CENTER','MOBILE_PHONE','TICKET','POS_ID','EMPLOYEE_NAME'], sep=None, engine='python')
print (df)

